name: Build VS Code Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x (required for build)
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install global Gulp
        run: npm install -g gulp

      - name: List available Gulp tasks
        run: gulp --tasks

      - name: Compile VS Code
        run: gulp compile

      - name: Build Windows User Installer (x64)
        run: gulp vscode-win32-x64-user-setup

      - name: Upload installer .exe
        uses: actions/upload-artifact@v4
        with:
          name: vscode-installer
          path: .build/win32/**/VSCodeSetup*.exe
