name: Build Sypha Installer

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install global Gulp
        run: npm install -g gulp

      - name: Create Sypha product.json
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path ".build/vscode-win32-x64/resources/app"
          @'
          {
            "nameShort": "Sypha",
            "nameLong": "Sypha Editor",
            "applicationName": "sypha",
            "dataFolderName": ".sypha",
            "win32AppUserModelId": "com.sypha.editor",
            "win32MutexName": "sypha"
          }
          '@ | Set-Content -Encoding UTF8 .build/vscode-win32-x64/resources/app/product.json

      - name: Compile Sypha
        run: gulp compile

      - name: Build Sypha (VS Code for Windows x64)
        run: gulp vscode-win32-x64

      - name: Build Sypha Installer (.exe)
        run: gulp vscode-win32-x64-user-setup

      - name: Upload Sypha Installer
        uses: actions/upload-artifact@v4
        with:
          name: sypha-installer
          path: .build/win32-user/**/VSCodeSetup*.exe
