name: Build Sypha Installer

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (v20.18.1)
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install global Gulp
        run: npm install -g gulp

      - name: Generate Sypha product.json
        run: |
          mkdir -p .build/vscode-win32-x64/resources/app
          echo ^{
            "nameShort": "Sypha",
            "nameLong": "Sypha Editor",
            "applicationName": "sypha",
            "dataFolderName": ".sypha",
            "win32AppUserModelId": "com.sypha.editor",
            "win32MutexName": "sypha",
            "licenseName": "MIT",
            "licenseUrl": "https://opensource.org/licenses/MIT",
            "reportIssueUrl": "https://github.com/YOUR_USERNAME/sypha/issues"
          ^} > .build/vscode-win32-x64/resources/app/product.json

      - name: Compile Sypha
        run: gulp compile

      - name: Build VS Code for Windows x64
        run: gulp vscode-win32-x64

      - name: Build Sypha Installer (Windows x64)
        run: gulp vscode-win32-x64-user-setup

      - name: Upload Sypha Setup Installer
        uses: actions/upload-artifact@v4
        with:
          name: sypha-installer
          path: .build/win32-user/**/VSCodeSetup*.exe
